language: java
cache:
  directories: $HOME/.gradle
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script: ./gradlew build

# Release the plugin via GitHub releases when pushing a tag
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "build/libs/easy-routes.jar"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
